title: "Jiseop Byeon"
email: jsbyeon@utexas.edu
description: "Research and project updates in Civil Engineering leveraging AR and Robotics."
url: "https://jiseop-byeon.github.io"
baseurl: "" # leave empty for user.github.io sites
repository: "jiseop-byeon/jiseop-byeon.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

paginate: 5
paginate_path: "/page:num/"

# Author info
author:
  name: "Jiseop Byeon"
  avatar: "/assets/images/profile.jpg"
  bio: "Graduate student in Civil Engineering at UT Austin. Researching AR, Sensors, and Robotics for smart civil systems."
  location: "Austin, TX"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:jsbyeon@utexas.edu"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jiseop-byeon"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/jiseop-byeon-887086208/"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/jiseop.byeon"

# Extras
locale: "en-US"
timezone: "America/Chicago"
theme_skin: "default"

include:
  - assets
